### ISSUE TITLE
Google Play warning - app doesn't target API level 26

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#884]
**Summary:** 

When releasing a new version on Google Play, after uploading the new APK it says:

~~~
Warnings
Your app currently targets API level 21 and must target at least API level 26 to ensure it is built on the latest APIs optimized for security and performance.

From August 2018, new apps must target at least Android 8.0 (API level 26).
From November 2018, app updates must target Android 8.0 (API level 26).

Tip: Change your app's target API level. Learn how.
~~~

Here's the link with more info:
https://developer.android.com/distribute/best-practices/develop/target-sdk

Blocked by:
- [x] Runtime permissions #330 - WIP PR at https://github.com/OneBusAway/onebusaway-android/pull/930
- [x] Notification channels - PR at https://github.com/OneBusAway/onebusaway-android/pull/935
- [x] Background execution of service for notifications - Rescheduling of reminders after boot - https://github.com/OneBusAway/onebusaway-android/issues/934
- [x] Background execution of service -  Embedded Social SDK - https://github.com/OneBusAway/onebusaway-android/issues/933

**Steps to reproduce:** 

Upload new release to Google Play

**Expected behavior:** 

Upload without warnings

**Observed behavior:** 

Google Play warns re: not targeting API level 26

**Device and Android version:** 

N/A

**Comment by barbeau** [comment]
This is blocked by at least runtime permissions, maybe others (we need to check):
https://github.com/OneBusAway/onebusaway-android/issues/330

**Comment by vinogeo** [comment]
Hi you can check this out How to Change Target API Level 26 or Above in Android Studio 
 http://www.oniverse.in/2018/08/how-to-change-target-api-level-26-or.html this might help

**Comment by barbeau** [comment]
Closing this, as we've checked all the items off the list necessary to target API level 26 in a release

**Comment by ahmedaniss25** [comment]
problem fixed here : https://youtu.be/o4iDJWjfUHs
